### ISSUE TITLE
Support redis on different port and SSL

### ISSUE THREAD

**Issue by stanleyz** [AzBuilder/terrakube-helm-chart#131] opened 2024-07-13 11:13 UTC
The Redis port should be customisable from Values, and also there should be options to turn on SSL connections to Redis.

**Comment by alfespa17** [comment] 2024-07-13 14:30
For now the only option is to use the environment variables that you can find here.

https://github.com/AzBuilder/terrakube/blob/81864245517958c356ecbf009901db5c20315be5/api/src/main/resources/application.properties#L158

https://github.com/AzBuilder/terrakube/blob/81864245517958c356ecbf009901db5c20315be5/api/src/main/resources/application.properties#L161

By the way I will close this one there is another issue for the same.

Duplicate of #115

**Closed** 2024-07-13 14:30 UTC
